dist: bionic
language: go
go:
  - 1.12.x
  - 1.13.x
env:
  - GO111MODULE=off
services:
  - docker
addons:
  apt:
    chrome: stable
before_install:
  - mkdir -p $GOPATH/src/github.com/chromedp
  - git clone https://github.com/c12o16h1/chromedp.git $GOPATH/src/github.com/c12o16h1/chromedp
  - cd $GOPATH/src/github.com/c12o16h1/chromedp
  - go get -d -t
script:
  - cd $GOPATH/src/github.com/c12o16h1/cdproto
  - go install ./...
  - cd $GOPATH/src/github.com/c12o16h1/chromedp
  - go test -v
  - go test -c
  - docker run --rm --volume=$PWD:/chromedp --entrypoint=/chromedp/chromedp.test --workdir=/chromedp --env=PATH=/headless-shell chromedp/headless-shell:latest -test.v
